In [2]:
import pandas as pd
import numpy as np

cols = ['A', 'B']
data = pd.DataFrame(np.array([[2,3],[1.02,1.2],[0.5,0.3]]),columns=cols)

In [3]:
data

A    B
0  2.00  3.0
1  1.02  1.2
2  0.50  0.3

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
#from sklearn.preprocessing import StandardScaler
#from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
sc = scaler.fit(data)
scaled_data = scaler.transform(data)

#scaler = preprocessing.MinMaxScaler(feature_range = (0,1))
#scaled_data = scaler.fit_transform(data[cols])

In [20]:
print(scaled_data)

[[ 1.          1.        ]
 [ 0.34666667  0.33333333]
 [ 0.          0.        ]]


In [21]:
scaler.inverse_transform(scaled_data)

array([[ 2.  ,  3.  ],
       [ 1.02,  1.2 ],
       [ 0.5 ,  0.3 ]])

In [26]:
from sklearn.preprocessing import StandardScaler


In [34]:
sc1 = StandardScaler()
X_train = sc1.fit_transform(data)
X_test = sc1.transform(data)


In [35]:
print(X_test)

[[ 1.32926676  1.33630621]
 [-0.24655754 -0.26726124]
 [-1.08270922 -1.06904497]]


In [36]:
sc1.inverse_transform(X_test)

array([[ 2.  ,  3.  ],
       [ 1.02,  1.2 ],
       [ 0.5 ,  0.3 ]])