## 你想对浮点数执行指定精度的舍入运算。
decimal 模块主要用在涉及到金融的领域。 在这类程序中，哪怕是一点小小的误差在计算过程中蔓延都是不允许的

In [1]:
print(round(1.27, 1))
print(round(1.25361,3))
a = 1627731
print(round(a, -1))
print(round(a, -2))
print(round(a, -3))

1.3
1.254
1627730
1627700
1628000


不要将舍入和格式化输出搞混淆了。 如果你的目的只是简单的输出一定宽度的数，你不需要使用 round() 函数。 而仅仅只需要在格式化的时候指定精度即可

In [2]:
x = 1.23456
print(format(x, '0.2f'))

1.23


### 你需要对浮点数执行精确的计算操作，并且不希望有任何小误差的出现
浮点数的一个普遍问题是它们并不能精确的表示十进制数。 并且，即使是最简单的数学运算也会产生小的误差, 这些错误是由底层CPU和IEEE 754标准通过自己的浮点单位去执行算术时的特征。 由于Python的浮点数据类型使用底层表示存储数据，因此你没办法去避免这样的误差。如果你想更加精确(并能容忍一定的性能损耗)，你可以使用 decimal 模块

In [3]:
a=4.2
b=2.1
c=a+b
print(c==6.3)

False


In [6]:
from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
d=a+b
print(d==Decimal('6.3'))

True


decimal 模块的一个主要特征是允许你控制计算的每一方面，包括数字位数和四舍五入运算。 为了这样做，你先得创建一个本地上下文并更改它的设置

In [7]:
from decimal import localcontext
a = Decimal('1.3')
b = Decimal('1.7')
print(a / b)
with localcontext() as ctx:
    ctx.prec = 3
    print(a / b)

0.7647058823529411764705882353
0.765


In [8]:
nums = [1.23e+18, 1, -1.23e+18]
print(sum(nums))

0.0


In [9]:
import math
math.fsum(nums)

1.0

### 你需要将数字格式化后输出，并控制数字的位数、对齐、千位分隔符和其他的细节

In [10]:
x = 1234.56789
print(format(x, '0.2f'))
print(format(x, '>10.1f'))
print(format(x, '<10.1f'))
print(format(x, '^10.1f'))
print(format(x, ','))
print(format(x, '0,.1f'))
print(format(x, 'e'))
print(format(x, '0.2E'))
print('The value is {:0,.2f}'.format(x))

1234.57
    1234.6
1234.6    
  1234.6  
1,234.56789
1,234.6
1.234568e+03
1.23E+03
The value is 1,234.57


### 你需要转换或者输出使用二进制，八进制或十六进制表示的整数。
use case: 
import os
os.chmod('script.py', 0o755)


In [11]:
y=1234
print(bin(y))
print(oct(y))
print(hex(y))
print(format(y,'b'))
print(format(y,'o'))
print(format(y,'x'))
print(int('4d2', 16))
print(int('10011010010', 2))

0b10011010010
0o2322
0x4d2
10011010010
2322
4d2
1234
1234


### 你有一个字节字符串并想将它解压成一个整数。或者，你需要将一个大整数转换为一个字节字符串
大整数和字节字符串之间的转换操作并不常见。 然而，在一些应用领域有时候也会出现，比如密码学或者网络

In [12]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
len(data)
print(int.from_bytes(data, 'little'))
print(int.from_bytes(data, 'big'))
x = 94522842520747284487117727783387188
print(x.to_bytes(16, 'big'))

69120565665751139577663547927094891008
94522842520747284487117727783387188
b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'


### 你写的最新的网络认证方案代码遇到了一个难题，并且你唯一的解决办法就是使用复数空间。 再或者是你仅仅需要使用复数来执行一些计算操作。

In [13]:
a = complex(2, 4)
b = 3 - 5j
print(a.real)
print(a.imag)
print(a.conjugate())
print(a+b)
print(abs(a))

2.0
4.0
(2-4j)
(5-1j)
4.47213595499958


In [16]:
import cmath
print(cmath.sin(a))
print(cmath.exp(a))
print(cmath.sqrt(-1))

(24.83130584894638-11.356612711218174j)
(-4.829809383269385-5.5920560936409816j)
1j


In [15]:
import numpy as np
c = np.array([2+3j, 4+5j, 6-7j, 8+9j])
print(c+2)
print(np.sin(c))

[  4.+3.j   6.+5.j   8.-7.j  10.+9.j]
[    9.15449915  -4.16890696j   -56.16227422 -48.50245524j
  -153.20827755-526.47684926j  4008.42651446-589.49948373j]


### 你想创建或测试正无穷、负无穷或NaN(非数字)的浮点数
测试一个NaN值得唯一安全的方法就是使用 math.isnan(), 想了解更多这些特殊浮点值的信息，可以参考IEEE 754规范

In [17]:
a = float('inf')
b = float('-inf')
c = float('nan')
print(math.isinf(a))
print(math.isinf(c))

True
False


### 你进入时间机器，突然发现你正在做小学家庭作业，并涉及到分数计算问题。 或者你可能需要写代码去计算在你的木工工厂中的测量值, fractions 模块可以被用来执行包含分数的数学运算

In [19]:
from fractions import Fraction
a = Fraction(5, 4)
print(a)
b = Fraction(7, 16)
print(b)
print(a+b)
c = a * b
print(c)
print(c.numerator)
print(c.denominator)
print(float(c)) #Converting to a float

# Converting a float to a fraction
x=3.75
y = Fraction(*x.as_integer_ratio())
print(y)

5/4
7/16
27/16
35/64
35
64
0.546875
15/4


### 你需要在大数据集(比如数组或网格)上面执行计算
涉及到数组的重量级运算操作，可以使用 NumPy 库, 官网 http://www.numpy.org

In [21]:
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
print(ax*2)
print(ax+10)
print(ax+ay)

[2 4 6 8]
[11 12 13 14]
[ 6  8 10 12]


In [22]:
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
print(m)
print(m.T)
print(m.I)


[[ 1 -2  3]
 [ 0  4  5]
 [ 7  8 -9]]
[[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]
[[ 0.33043478 -0.02608696  0.09565217]
 [-0.15217391  0.13043478  0.02173913]
 [ 0.12173913  0.09565217 -0.0173913 ]]


### 你想从一个序列中随机抽取若干元素，或者想生成几个随机数
random模块还包含基于均匀分布、高斯分布和其他分布的随机数生成函数。 比如， random.uniform() 计算均匀分布随机数， random.gauss() 计算正态分布随机数。 对于其他的分布情况请参考在线文档。

In [23]:
import random
values = [1, 2, 3, 4, 5, 6]
print(random.choice(values))
print(random.choice(values))
print(random.choice(values))

1
5
3


In [25]:
print(random.sample(values, 2))
print(random.sample(values, 3))

[2, 3]
[1, 4, 3]


In [26]:
random.shuffle(values)
print(values)

[5, 6, 2, 4, 3, 1]


In [28]:
#生成随机整数
a=random.randint(0,10)
print(a)
#为了生成0到1范围内均匀分布的浮点数
b=random.random()
print(b)
#random 模块使用 Mersenne Twister 算法来计算生成随机数。这是一个确定性算法， 但是你可以通过 random.seed() 函数修改初始化种子
c=random.seed(41)
print(c)

6
0.7326852754516092
None
